spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql:///sbms
    type: org.apache.commons.dbcp2.BasicDataSource
    password: dinesh9999
  application:
    name: bootIOCProject03-LayeredApp-RealTimeDI-MiniProject
