spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql:///sbms
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    password: dinesh9999
  application:
    name: bootIOCProject03-LayeredApp-RealTimeDI-MiniProject
dao:
  id: MySqlEmpDao
